spring:
  application:
    name: spring-batch
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./data/demo;AUTO_SERVER=TRUE
      driver-class-name: org.h2.Driver
      username: sa
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework.batch: DEBUG
    com.schooldevops.spring_batch: DEBUG