spring:
  application:
    name: spring-batch
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC&characterEncoding=UTF-8
      username: testuser
      password: 1234
  aop:
    auto: false
  batch:
    jdbc:
      initialize-schema: never

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always  # 항상 SQL 초기화 실행
      continue-on-error: true  # 오류 발생 시 계속 진행

spring.batch.job.name: JDBC_CURSOR_CHUNK_JOB
logging:
  level:
    org.springframework.batch: DEBUG
    com.schooldevops.spring_batch: DEBUG

    org:
      springframework:
        boot:
          autoconfigure: INFO
